import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "react-hot-toast";

import "./globals.css";
import Footer from "./footer/page";
import AuthProvider from "@/context/context";
import PrivateRoutes from "@/context/PrivateRoutes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crud App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthProvider>
          {/* <PrivateRoutes> */}
          <Toaster />
          {children}
          {/* <Footer /> */}
          {/* </PrivateRoutes> */}
        </AuthProvider>
      </body>
    </html>
  );
}
